name: publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish to antonio.prose.sh
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -v
        path: images/* posts/* support/*
        remote_path: /
        remote_user: antonio
        remote_host: prose.sh
        remote_key: ${{ secrets.PRIVATE_KEY }}
